# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'rubygems'
require 'bundler/setup'

require 'fakefs/safe'

require 'tlux'

Dir[File.expand_path('../support/**/*.rb', __FILE__)].each do |file|
  require(file)
end

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

def empty_tlux_dir!
  FakeFS do
    path = File.join(Dir.home, '.tlux')
    return unless Dir.exists?(path)
    Dir.foreach(path) { |filename| File.delete(File.join(path, filename)) if File.exists?(File.join(path, filename)) }
  end
end

def tlux_generated_dir
  File.join(Dir.home, '.tlux', 'generated')
end

def tlux_generated_file(file_name)
  File.join(tlux_generated_dir, file_name)
end

def tlux_config_file
  File.join(Dir.home, '.tlux')
end

def tlux_config_test_file
  File.join(tlux_config_file, 'test')
end
